### ISSUE TITLE
Support for Kotlin

### ISSUE THREAD

**Issue by gtludwig** [porscheinformatik/sonarqube-licensecheck#164] opened 2020-03-10 17:59 UTC
Hi,
I have tried this with a few Java projects and it works really nice.
I am trying to use this for a few Kotlin based projects and it doesn't.
I was wondering whether there is some plans to support Kotlin underway and, if not, how could I attempt at creating a scanner for it?

**Comment by derkoe** [comment] 2020-03-10 20:23
Are you using Maven for your Kotlin Build? I guess then it should work.

**Comment by gtludwig** [comment] 2020-03-11 09:21
No, I am using gradle for the Kotlin build. Dependencies are specified in the `plugins {}` section of the `build.gradle.kts` file and the build is triggered locally by `$ gradle clean build sonarqube`.

**Comment by derkoe** [comment] 2020-03-11 09:34
Ok, Gradle is currently not supported. You can use Maven.

**Comment by derkoe** [comment] 2020-03-11 09:35
Duplicate of #17, see also #160

**Closed by derkoe** 2020-03-11 09:35 UTC
